name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5

      - name: install dependencies
        run: go mod tidy
      
      - name: build
        run: go build ./...

      - name: test
        run: go test ./... -v -coverprofile=coverage.out

      - name: cleanup history
        uses: ./.github/actions/cleanup-history  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          days_old: 1
          page_count: 20